import type { DriveStep } from "driver.js";

export const submissionDetailSteps: DriveStep[] = [
  {
    element: '[data-tour="submission-hero-card"]',
    popover: {
      title: "Trial Score",
      description:
        "The headline card — composite score, archetype tag, and pass/fail status for this arena submission.",
      side: "bottom",
    },
  },
  {
    element: '[data-tour="submission-metric-grid"]',
    popover: {
      title: "Key Metrics",
      description:
        "Total Return, Avg Window, Win Rate, and Best/Worst Window at a glance. Red is bad, green is less bad.",
      side: "bottom",
    },
  },
  {
    element: '[data-tour="submission-report"]',
    popover: {
      title: "AI Report",
      description:
        "The Roast, Strengths, Weaknesses, and Recommendations — all generated by the AI judge. Read it and weep.",
      side: "top",
    },
  },
  {
    element: '[data-tour="submission-returns-chart"]',
    popover: {
      title: "Window Returns",
      description:
        "Bar chart of per-window returns. Click any bar to jump straight into that scenario's details.",
      side: "bottom",
    },
  },
  {
    element: '[data-tour="submission-heatlog"]',
    popover: {
      title: "Window Performance",
      description:
        "Every scenario window listed with status, return percentage, and quick links. Your strategy's report card.",
      side: "left",
    },
  },
  {
    element: '[data-tour="submission-window-row"]',
    popover: {
      title: "Inspect a Window",
      description:
        "Click any row to open the detail modal — equity curve, trade stats, and a link to the full replay.",
      side: "left",
    },
  },
];
